apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-frontend
  namespace: argocd-nginx
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginx-frontend
  template:
    metadata:
      labels:
        app: nginx-frontend
    spec:
      containers:
      - name: nginx-frontend
        image: nginx:latest
        resources:
          limits:
            memory: "32Mi"
            cpu: "100m"
        ports:
        - containerPort: 80
      initContainers:
      - name: init
        image: busybox
        command:
          - sh
          - -c
          - |
            echo "<h1 style='color: black; font-size: 32px; font-family: verdana'>argocd-nginx</h1>" > /usr/share/nginx/html/index.html

            echo "<p style='color: blue; font-size: 20px; font-family: verdana'>pod name: $(POD_NAME)</p>" >> /usr/share/nginx/html/index.html
            echo "<p style='color: blue; font-size: 20px; font-family: verdana'>pod ip: $(POD_IP)</p>" >> /usr/share/nginx/html/index.html
            echo "<p style='color: blue; font-size: 20px; font-family: verdana'>pod namespace: $(POD_NAMESPACE)</p>" >> /usr/share/nginx/html/index.html
            echo "<p style='color: blue; font-size: 20px; font-family: verdana'>pod serviceaccount: $(POD_SERVICE_ACCOUNT)</p>" >> /usr/share/nginx/html/index.html
            echo "<p style='color: blue; font-size: 20px; font-family: verdana'>pod node: $(NODE_NAME)</p>" >> /usr/share/nginx/html/index.html
        env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: POD_SERVICE_ACCOUNT
              valueFrom:
                fieldRef:
                  fieldPath: spec.serviceAccountName
        volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html
      volumes:
      - name: html-volume
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-frontend-service
  namespace: argocd-nginx
spec:
  type: LoadBalancer
  selector:
    app: nginx-frontend
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
