apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config-1
  namespace: nginx-token
data:
  index.html: |
    <HTML>
    <HEAD><TITLE>K8s Dashboard info</TITLE></HEAD>
    <BODY>
    <H1>info</H1>
    <i>empty1</i>
    </BODY></HTML
