apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config-1
  namespace: nginx-token
data:
  index.html: |
    <HTML>
    <HEAD><TITLE>K8s Dashboard info</TITLE></HEAD>
    <BODY>
    <H1>token</H1>
    <i>eyJhbGciOiJSUzI1NiIsImtpZCI6ImV2MUNXTURKc3lMZDBseFhkUEtxcmcxS1g3WnlMRG1ONlhsM28tZjhySVUifQ.eyJhdWQiOlsiaHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWwiXSwiZXhwIjoxNzI2NjU0NTMxLCJpYXQiOjE3MjY2NTA5MzEsImlzcyI6Imh0dHBzOi8va3ViZXJuZXRlcy5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsIiwianRpIjoiMzMxN2RjZDktMDY1Mi00N2E3LTlmMjYtZTU2ZjkwZjRmYThmIiwia3ViZXJuZXRlcy5pbyI6eyJuYW1lc3BhY2UiOiJrdWJlcm5ldGVzLWRhc2hib2FyZCIsInNlcnZpY2VhY2NvdW50Ijp7Im5hbWUiOiJhZG1pbi11c2VyIiwidWlkIjoiOWE3ZTc4MDQtMjBhZi00ZjA3LTg1MmYtZjMyOWYxZDMwMDEwIn19LCJuYmYiOjE3MjY2NTA5MzEsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDprdWJlcm5ldGVzLWRhc2hib2FyZDphZG1pbi11c2VyIn0.e40vCgMcPNPlIDECxy_dhOWHZpzvLjIiTnqaJrRsBrSiI7zZ24Jtoo66AK1ifsLTha6OcLk39Ab79WFw6ufwwP5bts_3PdjysLcmdxbig2CNK4_m1UFT1EQfhHEcdrBkErYX6jzukq-LvuNhnrOITs87RfCT6dF_Fb7swn8S2QLDgz09xYWlXwjNDgsppoCdvQo32VBScHay9cHtUmfIK1w_4jjdXaPN-K0HvsYvxm-Y7YV-oqRCXYz15kCSWII8tV_j0zVQ53Ux7eKHvmk8XbxSvj7_nOfMV7-n8_8JzIwXEfUczJIFNnZndfXYHRwj8JqZvG21mD8I17fm2RlzFQ</i>
    </BODY></HTML
